//psyhologists reducer
export const GET_PSHYHOLOGISTS = "GET_PSYHOLOGISTS";
export const ADD_PSYHOLOGIST = "ADD_PSYHOLOGIST";
export const DELETE_PSYHOLOGIST = "DELETE_PSYHOLOGIST";

//favorite reducer
export const GET_FAVORITE = "GET_FAVORITE";
export const ADD_FAVORITE = "ADD_FAVORITE";
export const DELETE_FAVORITE = "DELETE_FAVORITE";

export const GET_DISFAVORITE = "GET_DISFAVORITE";
export const ADD_DISFAVORITE = "ADD_DISFAVORITE";
export const DELETE_DISFAVORITE = "DELETE_DISFAVORITE";
